### ISSUE TITLE
你好，我在复现源代码时会出现次数过多时自动停止，请问您有出现这个问题吗？

### ISSUE THREAD

**Issue by C-SunRay** [Zydiii/PathTracing#1]
如图，一直到我减小到200次才得以成功……
![image](https://user-images.githubusercontent.com/57622222/167676071-6c776faa-b5f9-4664-af3c-1b20716c772d.png)

**Comment by Zydiii** [comment]
你好，我自己运行高采样率的话在 debug 模式下会卡住，换成 release 就不会，可能因为这个程序效率实在太低了。。以及可以注释掉 OpenMP 试试？

**Comment by C-SunRay** [comment]
好的 感谢
